name: Auto Merge Main to Deployment

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Merge main into deployment
      run: |
        git checkout deployment
        git merge main
        git push origin deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
