name: Auto Merge Main to Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: List all branches
      run: git branch -a

    - name: Fetch all branches
      run: git fetch origin

    - name: Checkout deployment branch
      run: git checkout deployment

    - name: Merge main into deployment
      run: |
        git merge main --allow-unrelated-histories || true
        git restore --source=HEAD --staged .gitignore node_modules/ .env *.log build/ README.md src/utils .ejsbrc.json .github/
        git commit -m "Merge main into deployment, excluding specified files"
        git push origin deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
